In [2]:
from ultralytics import YOLO
import cv2
import torch
import math

In [3]:
model = YOLO(r"best.pt")

In [4]:
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
device

device(type='cpu')

In [7]:
video = cv2.VideoCapture(0)

width = int(video.get(cv2.CAP_PROP_FRAME_WIDTH))
height = int(video.get(cv2.CAP_PROP_FRAME_HEIGHT))

while True:
    
    ret, frame = video.read()
    
    frame = cv2.resize(frame,(width,height),interpolation = cv2.INTER_AREA)
        
    results = model.predict(frame, conf=0.7, stream = True,device = device)
    
    for result in results:
        boxes = result.boxes.cpu().numpy()  
        for box in boxes:
            r = box.xyxy[0].astype(int)
            print(r)
            cv2.rectangle(frame, r[:2], r[2:], (0, 255, 0), 2)

            confidence = math.ceil((box.conf[0]*100))/100
            print("Confidence --->",confidence)
            font = cv2.FONT_HERSHEY_SIMPLEX
  
            # org
            org = (r[0], r[1])
            
            # fontScale
            fontScale = 1
            
            # Blue color in BGR
            color = (255, 0, 255)
            
            # Line thickness of 2 px
            thickness = 2
            
            # Using cv2.putText() method
            frame = cv2.putText(frame, f"{confidence}", org, font,
                                fontScale, color, thickness, cv2.LINE_AA)
            
            #cv2.putText(frame, confidence,[r[:1], r[1:2]], cv2.FONT_HERSHEY_SIMPLEX, (255,0,0), 2, cv2.LINE_AA)

    cv2.imshow("input", frame)

    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
        
video.release()
cv2.destroyAllWindows()        


0: 480x640 1 face, 226.1ms
Speed: 4.0ms preprocess, 226.1ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)



[269 236 416 444]
Confidence ---> 0.81


0: 480x640 1 face, 221.4ms
Speed: 2.0ms preprocess, 221.4ms inference, 0.0ms postprocess per image at shape (1, 3, 480, 640)



[269 235 415 447]
Confidence ---> 0.81


0: 480x640 1 face, 231.1ms
Speed: 0.0ms preprocess, 231.1ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)



[268 235 414 445]
Confidence ---> 0.83


0: 480x640 1 face, 222.1ms
Speed: 0.0ms preprocess, 222.1ms inference, 0.0ms postprocess per image at shape (1, 3, 480, 640)



[267 236 413 444]
Confidence ---> 0.81


0: 480x640 1 face, 224.2ms
Speed: 0.0ms preprocess, 224.2ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)



[268 238 416 445]
Confidence ---> 0.78


0: 480x640 1 face, 202.1ms
Speed: 3.0ms preprocess, 202.1ms inference, 0.0ms postprocess per image at shape (1, 3, 480, 640)



[269 236 417 454]
Confidence ---> 0.81


0: 480x640 1 face, 229.2ms
Speed: 0.0ms preprocess, 229.2ms inference, 0.0ms postprocess per image at shape (1, 3, 480, 640)



[274 229 430 449]
Confidence ---> 0.77


0: 480x640 1 face, 271.1ms
Speed: 5.6ms preprocess, 271.1ms inference, 0.0ms postprocess per image at shape (1, 3, 480, 640)



[277 230 436 455]
Confidence ---> 0.81


0: 480x640 1 face, 258.9ms
Speed: 2.0ms preprocess, 258.9ms inference, 0.0ms postprocess per image at shape (1, 3, 480, 640)



[280 221 441 445]
Confidence ---> 0.8


0: 480x640 1 face, 271.0ms
Speed: 0.0ms preprocess, 271.0ms inference, 0.0ms postprocess per image at shape (1, 3, 480, 640)



[277 228 439 451]
Confidence ---> 0.76


0: 480x640 1 face, 279.8ms
Speed: 0.0ms preprocess, 279.8ms inference, 0.0ms postprocess per image at shape (1, 3, 480, 640)



[276 224 434 444]
Confidence ---> 0.76


0: 480x640 1 face, 263.3ms
Speed: 0.0ms preprocess, 263.3ms inference, 0.0ms postprocess per image at shape (1, 3, 480, 640)



[276 230 432 442]
Confidence ---> 0.8


0: 480x640 1 face, 263.9ms
Speed: 2.0ms preprocess, 263.9ms inference, 0.0ms postprocess per image at shape (1, 3, 480, 640)



[274 230 425 441]
Confidence ---> 0.81


0: 480x640 1 face, 284.9ms
Speed: 0.0ms preprocess, 284.9ms inference, 0.0ms postprocess per image at shape (1, 3, 480, 640)



[274 237 423 435]
Confidence ---> 0.83


0: 480x640 1 face, 263.2ms
Speed: 4.3ms preprocess, 263.2ms inference, 0.0ms postprocess per image at shape (1, 3, 480, 640)



[271 231 420 443]
Confidence ---> 0.82


0: 480x640 1 face, 263.1ms
Speed: 4.7ms preprocess, 263.1ms inference, 0.0ms postprocess per image at shape (1, 3, 480, 640)



[271 229 424 452]
Confidence ---> 0.8


0: 480x640 1 face, 258.8ms
Speed: 3.0ms preprocess, 258.8ms inference, 0.0ms postprocess per image at shape (1, 3, 480, 640)



[271 234 425 449]
Confidence ---> 0.8


0: 480x640 1 face, 272.0ms
Speed: 0.0ms preprocess, 272.0ms inference, 0.0ms postprocess per image at shape (1, 3, 480, 640)



[272 228 424 432]
Confidence ---> 0.8


0: 480x640 1 face, 267.1ms
Speed: 2.0ms preprocess, 267.1ms inference, 0.0ms postprocess per image at shape (1, 3, 480, 640)



[271 232 426 450]
Confidence ---> 0.8


0: 480x640 1 face, 268.1ms
Speed: 0.0ms preprocess, 268.1ms inference, 0.0ms postprocess per image at shape (1, 3, 480, 640)



[270 232 426 447]
Confidence ---> 0.81


0: 480x640 1 face, 261.8ms
Speed: 3.7ms preprocess, 261.8ms inference, 0.0ms postprocess per image at shape (1, 3, 480, 640)



[270 229 422 444]
Confidence ---> 0.77


0: 480x640 1 face, 277.6ms
Speed: 0.0ms preprocess, 277.6ms inference, 0.0ms postprocess per image at shape (1, 3, 480, 640)



[269 236 417 441]
Confidence ---> 0.83


0: 480x640 1 face, 270.4ms
Speed: 3.9ms preprocess, 270.4ms inference, 0.0ms postprocess per image at shape (1, 3, 480, 640)



[270 234 420 433]
Confidence ---> 0.83


0: 480x640 1 face, 272.4ms
Speed: 3.0ms preprocess, 272.4ms inference, 0.0ms postprocess per image at shape (1, 3, 480, 640)



[269 232 418 438]
Confidence ---> 0.84


0: 480x640 1 face, 267.0ms
Speed: 3.0ms preprocess, 267.0ms inference, 0.0ms postprocess per image at shape (1, 3, 480, 640)


[269 232 419 437]
Confidence ---> 0.82
